name: ocean
description: A social commerce platform where buyers and sellers connect
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # Storage & Database
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Media & Files
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  
  # AR Features
  ar_flutter_plugin: ^0.7.3
  
  # Maps & Location
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
  # Payments
  flutter_stripe: ^11.1.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.0
  hive_generator: ^2.0.1
  
  # Analysis and formatting
  analyzer: ^6.8.0
  dart_style: ^2.3.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/ar_models/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: LeckerliOne
      fonts:
        - asset: assets/fonts/LeckerliOne-Regular.ttf